### PR TITLE
Added FB data extraction

### PR DESCRIPTION
**Pull request by Neitsch**
I don't have an iPhone, but wanted to use this analysis (really cool presentation btw). So I applied it to my FB data. It's not quite as smooth as with the iPhone, since it requires to download your archive and then convert it to json (https://github.com/ownaginatious/fbchat-archive-parser). In addition I'm not very familiar with Python or Pandas. Any interest in integrating this? Then I can put some more effort into getting everything right.

### CODE REVIEW

**Comment by mdezube** [comment]
Hey Neitsch,

Thanks for the contribution, and I'm glad to hear you enjoyed the talk! I think integrating facebook messenger is a fantastic idea.  I'd be happy to integrate this, but do have a few comments: 

1. Instead of using `table_connector`, how about renaming that to `iphone_connector` and then creating a new file named `fb_dump_connector`, documenting it and adding your logic there?  You can then include clear documentation and error checking for opening the json bundle
2. Let's add the new pip dependency to an `optional-requirements.txt` file and update the README to mention it
3.  I'll likely have to update some cases in the IPython notebook but would be happy to do so

Are you interested in following through on this?  If so, I'd recommend I create a branch for you and we can work in that.  The benefit is as you complete chunks you can send them my way for review and submission.  Also as a heads up, I tend to give very thorough reviews :), interested in line by line reviews of your Python?

**Comment by mdezube** [comment]
Also thinking fb_archive_connector would be better than fb_dump_connector

**Comment by Neitsch** [comment]
Hey mdezube,

1. Separating those two into different classes is a great idea! Will do so
2. Will add that
3. I can take care of it

Yes, I absolutely want to move forward with this! Reviews are the best way to improve, thorough are the best 👍 
I'll start by separating the two connectors and then we'll go from there :)

Thank you!

**Comment by Neitsch** [comment]
Hey, working on putting the parsed data in a DF. What exactly is required for the address_book and the message_df? I think you only need full_name for address_book and for the message_df you need (message_id,is_from_me,phone_or_email,text,date). I recall from the talk that address_book also requires birthday, is that right? Am I missing anything else?

**Comment by mdezube** [comment]
Fantastic, looking forward to working with you on this.  And I agree regarding code reviews, glad to hear we're in alignment :)

There's a difference between what the dataframes contain and what they actually require.  E.g. although they include birthday, chat_id, message_id none of these are actually required for the rest of the analysis, they're included solely because they're available in the sqlite databases and could be used for additional analysis.

In your case what I'd do is:

1. Generate an `address_book` with `full_name` and `birthday` (if you have the birthday available, if not just include full_name).  Return this to the notebook and name it `fb_address_book`.  Note the other `address_book` is not used anywhere later in the notebook so keeping it at None is acceptable.
2. In the `fb_archive_connector` generate a `fully_merged_messages_df` which contains `text`, `date`, `is_from_me` and `full_name` (and birthday if you have it), none of the other fields are required.
3. Document the cell to clarify that there's now an option for which data source you want to use.

Offhand I don't think it's worth combining Facebook messages with texts since they're different mediums, have different vernaculars and reconciling names may not be worth it.

I'm also very welcome to other thoughts!

**Comment by Neitsch** [comment]
Closing in favor of #14

**Pull request closed without merging**
